<?xml version="1.0" encoding="utf-8"?><Database Name="SmartBussinessCloud" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\SmartBussinessCloud.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SmartBussinessCloudConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[user]" Member="users">
    <Type Name="user">
      <Column Name="u_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="firstname" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="lastname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="wallpaper" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="user_userApp" Member="userApps" ThisKey="u_id" OtherKey="u_id" Type="userApp" />
    </Type>
  </Table>
  <Table Name="dbo.userApp" Member="userApps">
    <Type Name="userApp">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="u_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="app_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="user_userApp" Member="user" ThisKey="u_id" OtherKey="u_id" Type="user" IsForeignKey="true" />
      <Association Name="app_userApp" Member="app" ThisKey="app_id" OtherKey="app_id" Type="app" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.category" Member="categories">
    <Type Name="category">
      <Column Name="cat_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="cat_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="cat_description" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="cat_image" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.app" Member="apps">
    <Type Name="app">
      <Column Name="app_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="app_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="link" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="logo_path" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="app_info" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="category" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="app_description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="app_userApp" Member="userApps" ThisKey="app_id" OtherKey="app_id" Type="userApp" />
    </Type>
  </Table>
</Database>